import{a as u,S as P,i as a}from"./assets/vendor-BSTwZ_tR.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))l(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&l(s)}).observe(document,{childList:!0,subtree:!0});function n(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function l(t){if(t.ep)return;t.ep=!0;const r=n(t);fetch(t.href,r)}})();const q="https://pixabay.com/api/",x="52251600-fd545eaf39516c2667db2508b";u.defaults.baseURL=q;async function f(o,e){return(await u.get("",{params:{key:x,q:o,page:e,per_page:15,image_type:"photo",orientation:"horizontal",safesearch:!0}})).data}const m=document.querySelector(".gallery"),g=document.querySelector(".loader"),p=document.querySelector(".load-more"),B=new P(".gallery a",{captionsData:"alt",captionPosition:"bottom",captions:!0,captionDelay:250});function h(o){const e=o.map(({webformatURL:n,largeImageURL:l,tags:t,likes:r,views:s,comments:S,downloads:v})=>`<li class="gallery-item">
          <a class="gallery-link" href="${l}">
            <img class="gallery-image" src="${n}" alt="${t}" />
            <div class="card">
          <ul class="card-list">
            <li class="card-item">Likes<p class="text">${r}</p></li>
            <li class="card-item">Views <p class="text">${s}</p></li>
            <li class="card-item">Comments <p class="text">${S}</p> </li>
            <li class="card-item">Downloads <p class="text">${v}</p></li>
          </ul>
        </div>
          </a>
        </li>`).join("");m.insertAdjacentHTML("beforeend",e),B.refresh()}function M(){m.innerHTML=""}function y(){g.classList.remove("is-hidden")}function d(){g.classList.add("is-hidden")}function R(){p.classList.remove("is-hidden")}function b(){p.classList.add("is-hidden")}const L=document.querySelector("form"),$=document.querySelector(".load-more");let i=1;const w=15;let c=null;L.addEventListener("submit",E);$.addEventListener("click",k);async function E(o){if(o.preventDefault(),i=1,b(),M(),c=o.currentTarget.elements["search-text"].value.trim(),!c){d(),a.warning({message:"Please enter a search term!",position:"topRight",messageColor:"#fff",backgroundColor:"#ef4040",icon:""});return}y();try{const e=await f(c,i);if(e.hits.length===0){a.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",messageColor:"#fff",backgroundColor:"#ef4040",icon:""});return}h(e.hits),setTimeout(C,0),e.totalHits>w?R():a.info({message:"We're sorry, but you've reached the end of search results.",messageColor:"#fff",backgroundColor:"#59a10d",position:"bottomRight",icon:""})}catch(e){console.log(e),a.error({position:"topRight",message:"Something went wrong. Please try again!",messageColor:"#fff",backgroundColor:"#ef4040",icon:""})}finally{d(),L.reset()}}async function k(){y(),i+=1;try{const o=await f(c,i);h(o.hits),C();const e=Math.ceil(o.totalHits/w);i===e&&(b(),a.info({message:"We're sorry, but you've reached the end of search results.",messageColor:"#fff",backgroundColor:"#59a10d",position:"bottomRight",icon:""}))}catch(o){console.log(o)}finally{d()}}function C(){const o=document.querySelector(".gallery-item");if(o){const e=o.getBoundingClientRect().height;requestAnimationFrame(()=>{window.scrollBy({top:e*2,behavior:"smooth"})})}}
//# sourceMappingURL=index.js.map
